-- Replaces the customer_type enum:
--   Old: celebrity, athlete, influencer, executive, creator, other
--   New: actor, athlete, influencer, performer
--
-- Existing rows using a dropped value (celebrity, executive, creator, other)
-- are bulk-set to 'performer' as a safe default. Correct individual records
-- afterward in Admin > Users if needed.
--
-- IMPORTANT: Postgres will not let you use a brand-new enum value in the
-- same transaction that added it ("unsafe use of new value ... of enum
-- type"). Run this file in TWO SEPARATE executions/transactions:
--   1. Run 0001a_customer_type_add_values.sql first, on its own.
--   2. Then run 0001b_customer_type_remap_and_swap.sql, on its own.
--
-- After both run, `npm run db:push` should see no further diff for this enum.
